# Generated by Django 5.2.3 on 2025-06-28 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.CharField()),
                ('tempo_preparo', models.IntegerField(max_length=100)),
                ('rendimento', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=100)),
                ('date_prato', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
