# Generated by Django 5.2.2 on 2025-07-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_alter_prato_tempo_preparo'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario'),
            preserve_default=False,
        ),
    ]
