# Generated by Django 5.2.4 on 2025-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0004_prato_foto_prato_prato_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prato',
            name='rendimento',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
