# Generated by Django 5.2.4 on 2025-07-11 20:17

import churras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0005_alter_prato_categoria_alter_prato_rendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='foto_prato',
            field=models.ImageField(blank=True, upload_to=churras.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='prato',
            name='rendimento',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
